# Generated by Django 5.1.1 on 2024-09-17 11:23

import ckeditor_uploader.fields
import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
