# Generated by Django 5.1.1 on 2024-09-17 11:27

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_image_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Portada del curso'),
        ),
    ]
