# Generated by Django 5.1.1 on 2024-10-14 15:40

import ckeditor_uploader.fields
import django.utils.timezone
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('mostrar_home', models.BooleanField(default=False, verbose_name='Mostrar en la home')),
                ('portada_imagen', thumbnails.fields.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Portada del blog')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
