# Generated by Django 5.1.1 on 2024-10-15 07:50

import ckeditor_uploader.fields
import django.utils.timezone
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publicacion_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicacion')),
                ('show_home', models.BooleanField(default=False, verbose_name='Mostrar en la home')),
                ('blog_image', thumbnails.fields.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Portada del blog')),
            ],
            options={
                'verbose_name': 'publicacion',
                'verbose_name_plural': 'publicaciones',
            },
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
