# Generated by Django 5.1.1 on 2024-10-15 11:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_options_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='contenido'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Título'),
        ),
    ]
