# Generated by Django 5.0.7 on 2024-10-15 14:36

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_content_en_post_content_es_post_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='post/images/', verbose_name='Portada del curso'),
        ),
    ]
