# Generated by Django 5.1.1 on 2024-09-16 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido del curso'),
        ),
    ]
