# Generated by Django 5.1.1 on 2024-09-17 10:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido del curso'),
        ),
    ]
