# Generated by Django 5.1.1 on 2024-10-14 16:02

import ckeditor_uploader.fields
import django.utils.timezone
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido del curso')),
                ('link_llamada', models.URLField(verbose_name='Enlace de llamada')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('mostrar_home', models.BooleanField(default=False, verbose_name='Mostrar en la home')),
                ('toc', models.FileField(blank=True, null=True, upload_to='courses/toc/', verbose_name='Temario')),
                ('portada_curso', thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
