# Generated by Django 5.1.1 on 2024-10-15 08:03

import ckeditor.fields
import django.utils.timezone
import thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_curso_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del curso')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido del curso')),
                ('call_link', models.URLField(verbose_name='Enlace de llamada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación')),
                ('show_home', models.BooleanField(default=False, verbose_name='Mostrar en la home')),
                ('toc', models.FileField(blank=True, null=True, upload_to='courses/toc/', verbose_name='Temario')),
                ('course_image', thumbnails.fields.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='Portada del curso')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
