# Generated by Django 5.1.1 on 2024-10-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_delete_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
