# Generated by Django 5.1.1 on 2024-10-14 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_contactado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario que ha dejado en la Web')),
                ('fecha_creado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('contactado', models.BooleanField(default=False, verbose_name='¿Se ha contactado con el?')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
