# Generated by Django 5.1.1 on 2024-10-15 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('comentario', models.TextField(verbose_name='Comentario que ha dejado en la web')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de creación')),
                ('contactado', models.BooleanField(default=False, verbose_name='¿Se ha contactado con él?')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
