# Generated by Django 5.1.1 on 2024-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_libro_idioma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles')], default='ES', max_length=2),
        ),
    ]
