# Generated by Django 5.1.1 on 2024-09-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_historicalautor_historicaleditorial_historicallibro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEditorial',
        ),
    ]
