# Generated by Django 5.1.1 on 2024-09-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_delete_historicaleditorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLibro',
        ),
    ]
