# Generated by Django 5.1.1 on 2024-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_delete_historicallibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'Ingles'), ('IT', 'Italiano')], default='ES', max_length=2),
        ),
    ]
