# Generated by Django 5.1.1 on 2024-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_libro_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editorial',
            options={'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo_es',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
