# Generated by Django 5.1.1 on 2024-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_autor_options_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(to='books.autor'),
        ),
    ]
